import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';

const PrivacyPolicyPage: React.FC = () => {
  useEffect(() => {
    // Update page title
    document.title = 'Privacy Policy - A Team Edventures';
    
    // Scroll to top on page load
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      {/* Page Header */}
      <div className="bg-gradient-to-r from-primary-700 to-primary-900 py-16">
        <div className="container-custom">
          <div className="text-center">
            <h1 className="text-white text-4xl font-bold mb-4">Privacy Policy</h1>
            <p className="text-white/80">
              Last Updated: May 1, 2025
            </p>
          </div>
        </div>
      </div>

      {/* Privacy Policy Content */}
      <div className="py-16 bg-white">
        <div className="container-custom max-w-4xl">
          <div className="prose prose-lg max-w-none">
            <p>
              A Team Edventures ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by A Team Edventures.
            </p>
            
            <p>
              This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, A Team Edventures. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
            </p>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Definitions and Key Terms</h2>
            <p>
              To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
              <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to A Team Edventures, that is responsible for your information under this Privacy Policy.</li>
              <li><strong>Country:</strong> where A Team Edventures or the owners/founders of A Team Edventures are based, in this case is United States.</li>
              <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the A Team Edventures Service to manage the relationships with your consumers or service users.</li>
              <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit A Team Edventures and use the services.</li>
              <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information allows for the identification or identifiability of a natural person.</li>
              <li><strong>Service:</strong> refers to the service provided by A Team Edventures as described in the relative terms (if available) and on this platform.</li>
              <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
              <li><strong>Website:</strong> A Team Edventure's site, which can be accessed via this URL: www.ateamedventures.com</li>
              <li><strong>You:</strong> a person or entity that is registered with A Team Edventures to use the Services.</li>
            </ul>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Information We Collect</h2>
            <p>
              We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Name / Username</li>
              <li>Phone Numbers</li>
              <li>Email Addresses</li>
              <li>Job Titles</li>
              <li>Billing Addresses</li>
              <li>Debit/credit card numbers</li>
              <li>Age</li>
              <li>Password</li>
            </ul>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">How We Use Your Information</h2>
            <p>
              We use the information we collect in various ways, including to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide, operate, and maintain our website</li>
              <li>Improve, personalize, and expand our website</li>
              <li>Understand and analyze how you use our website</li>
              <li>Develop new products, services, features, and functionality</li>
              <li>Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes</li>
              <li>Send you emails</li>
              <li>Find and prevent fraud</li>
            </ul>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Log Files</h2>
            <p>
              A Team Edventures follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.
            </p>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Cookies and Web Beacons</h2>
            <p>
              Like any other website, A Team Edventures uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.
            </p>
            <p>
              For more general information on cookies, please read <a href="https://www.cookieconsent.com/what-are-cookies/" className="text-primary-600 hover:text-primary-800">"What Are Cookies"</a>.
            </p>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Third-Party Privacy Policies</h2>
            <p>
              A Team Edventure's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options.
            </p>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>
            <p>
              Under the CCPA, among other rights, California consumers have the right to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</li>
              <li>Request that a business delete any personal data about the consumer that a business has collected.</li>
              <li>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</li>
              <li>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</li>
            </ul>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">GDPR Data Protection Rights</h2>
            <p>
              We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>The right to access – You have the right to request copies of your personal data.</li>
              <li>The right to rectification – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.</li>
              <li>The right to erasure – You have the right to request that we erase your personal data, under certain conditions.</li>
              <li>The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions.</li>
              <li>The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions.</li>
              <li>The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</li>
              <li>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</li>
            </ul>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Children's Information</h2>
            <p>
              Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.
            </p>
            <p>
              A Team Edventures does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.
            </p>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Changes to This Privacy Policy</h2>
            <p>
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
            </p>
            <p>
              We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
            </p>
            <p>
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>
            
            <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please contact us:
            </p>
            <ul className="list-none space-y-2">
              <li>By email: privacy@ateamedventures.com</li>
              <li>By phone number: (123) 456-7890</li>
              <li>By mail: 123 Team Building Avenue, Adventure City, TX 12345</li>
            </ul>
          </div>
          
          <div className="mt-12 text-center">
            <Link to="/contact" className="btn-primary">
              Contact Us With Questions
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicyPage;